export default {
  homeButtonIcon: require("../../../assets/home.png"),
  blackHeartIcon: require("../../../assets/black-heart.png"),
  mailIcon: require("../../../assets/mail.png"),
  profileIcon: require("../../../assets/profile.png"),
  heartIcon: require("../../../assets/heart.png"),
  locationIcon: require("../../../assets/location.png"),
  whiteLocationIcon:require("../../../assets/location-white.png"),
  filterIcon: require("../../../assets/Icon.png"),
  searchIcon: require("../../../assets/Shape.png"),
  starIcon: require("../../../assets/star.png"),
  editProfileButtonIcon:require("../../../assets/editProfile.png"),
  verifiedIcon:require("../../../assets/verified.png"),
  house1:require("../../../assets/house1.jpg"),
  house2v1: require("../../../assets/house2.jpg"),
  house2v2: require("../../../assets/house2v2.jpg"),
  house2v3: require("../../../assets/house2v3.jpg"),
  rentProfilePic: require("../../../assets/profilePic.png"),
  holderProfilePic: require("../../../assets/holderProfilePicture.png"),
  holderBackgroundPic:require("../../../assets/holderBackgroundPicture.png"),
  backButton:require("../../../assets/backButton.png"),
  languageIcon:require("../../../assets/languageIcon.png"),
  messageIcon:require("../../../assets/messageIcon.png"),
  callIcon:require("../../../assets/callIcon.png"),
  bedRoomsIcon:require("../../../assets/bedRoomsIcon.png"),
  bathRoomIcon:require("../../../assets/bathRoomIcon.png"),
  parkingIcon:require("../../../assets/parking.png"),
};
